"""Mokumitsu: wind- and fire-aware renewal research for dense Japanese neighbourhoods.

The package is deliberately independent of Houdini.  It owns the district schema,
organic generation, legal-access proxies, fire screening, staged renewal and Pareto
selection.  Geometry editors and CFD engines are adapters around this research core.
"""

from __future__ import annotations

from . import geometry
from .comfort import Comfort, Thresholds, comfort, open_mask
from .district import (
    ARTICLE_42_1,
    ARTICLE_42_2,
    NON_ROAD,
    AccessAssessment,
    DistrictBuilding,
    DistrictSummary,
    Frontage,
    MokumitsuConfig,
    MokumitsuDistrict,
    MorphologySummary,
    Parcel,
    PriorityWeights,
    RenewalCandidate,
    RoadSegment,
    assess_access,
    district_summary,
    generate_mokumitsu,
    generate_mokumitsu_grid,
    load_district,
    morphology_summary,
    renewal_priorities,
    road_adjacency,
    save_district,
    validate_district,
)
from .feasibility import (
    JointProjectCost,
    JointRenewalFeasibilityPhase,
    JointRenewalFeasibilityPolicy,
    JointRenewalFeasibilityResult,
    JointRenewalFeasibilitySummary,
    JointRightsAllocation,
    evaluate_joint_renewal_feasibility,
    save_joint_renewal_feasibility,
)
from .fire import (
    FireAwareRenewalCandidate,
    FireRiskResult,
    FireScenario,
    SpreadEdge,
    build_fire_graph,
    fire_aware_renewal_priorities,
    simulate_fire_spread,
)
from .joint_renewal import (
    JointBuildingPlacement,
    JointOpenSpace,
    JointRenewalCandidate,
    JointRenewalPlan,
    JointRenewalPolicy,
    JointRenewalStep,
    apply_joint_redevelopment,
    joint_redevelopment_variants,
    joint_renewal_candidates,
    joint_wind_objective,
    optimize_joint_renewal,
)
from .model import FnoModel, load_model
from .organic import generate_organic_mokumitsu
from .pareto import (
    JointRenewalAlternative,
    JointRenewalObjectives,
    ParetoRenewalPolicy,
    ParetoRenewalResult,
    evaluate_joint_renewal_pareto,
    pareto_front,
)
from .renewal import (
    RenewalAction,
    RenewalPhase,
    RenewalPhaseMetrics,
    RenewalPolicy,
    RenewalTrajectory,
    save_renewal_trajectory,
    simulate_renewal_trajectory,
)
from .wind import (
    DirectionalWindMetrics,
    DistrictWindMetrics,
    SummerWindScenario,
    WindDirection,
    WindZoneMetrics,
    add_wind_to_trajectory,
    district_wind_masks,
    evaluate_district_wind,
    predict_directional_wind,
)

__all__ = [
    "ARTICLE_42_1",
    "ARTICLE_42_2",
    "AccessAssessment",
    "Comfort",
    "DirectionalWindMetrics",
    "DistrictBuilding",
    "DistrictSummary",
    "DistrictWindMetrics",
    "FireAwareRenewalCandidate",
    "FireRiskResult",
    "FireScenario",
    "FnoModel",
    "Frontage",
    "JointBuildingPlacement",
    "JointOpenSpace",
    "JointProjectCost",
    "JointRenewalFeasibilityPhase",
    "JointRenewalFeasibilityPolicy",
    "JointRenewalFeasibilityResult",
    "JointRenewalFeasibilitySummary",
    "JointRenewalAlternative",
    "JointRenewalCandidate",
    "JointRenewalObjectives",
    "JointRenewalPlan",
    "JointRenewalPolicy",
    "JointRenewalStep",
    "JointRightsAllocation",
    "MokumitsuConfig",
    "MokumitsuDistrict",
    "MorphologySummary",
    "NON_ROAD",
    "Parcel",
    "ParetoRenewalPolicy",
    "ParetoRenewalResult",
    "PriorityWeights",
    "RenewalAction",
    "RenewalCandidate",
    "RenewalPhase",
    "RenewalPhaseMetrics",
    "RenewalPolicy",
    "RenewalTrajectory",
    "RoadSegment",
    "SpreadEdge",
    "SummerWindScenario",
    "Thresholds",
    "WindDirection",
    "WindZoneMetrics",
    "add_wind_to_trajectory",
    "apply_joint_redevelopment",
    "assess_access",
    "build_fire_graph",
    "comfort",
    "district_summary",
    "district_wind_masks",
    "evaluate_district_wind",
    "evaluate_joint_renewal_feasibility",
    "evaluate_joint_renewal_pareto",
    "fire_aware_renewal_priorities",
    "generate_mokumitsu",
    "generate_mokumitsu_grid",
    "generate_organic_mokumitsu",
    "geometry",
    "joint_redevelopment_variants",
    "joint_renewal_candidates",
    "joint_wind_objective",
    "load_district",
    "load_model",
    "morphology_summary",
    "open_mask",
    "optimize_joint_renewal",
    "pareto_front",
    "predict_directional_wind",
    "renewal_priorities",
    "road_adjacency",
    "save_district",
    "save_joint_renewal_feasibility",
    "save_renewal_trajectory",
    "simulate_fire_spread",
    "simulate_renewal_trajectory",
    "validate_district",
]
